version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout

      - run:
          name: genarate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed

      - restore_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs

      - run:
          name: generate keystore debug
          command: |
            [ ! -d ~/.android ] && mkdir ~/.android
            echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - run:
          name: grand access gradlew
          command: |
            chmod +x gradlew

      - run:
          name: gradlew dependencies
          command: |
            ./gradlew dependencies

      - run:
          name: gradle clean build
          command: |
            ./gradlew clean build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - store_test_results:
          path: app/build/test-results

      - save_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle

  build_aab:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout

      - run:
          name: genarate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed

      - restore_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

      - run:
          name: generate keystore debug
          command: |
            [ ! -d ~/.android ] && mkdir ~/.android
            echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs

      - run:
          name: gradlew grand access
          command: |
            chmod +x gradlew

      - run:
          name: gradle dependencies
          command: |
            ./gradlew dependencies

      - save_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle

      - run:
          name: gradle bundleRelease
          command: |
            ./gradlew clean bundleRelease

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs
          destination: outputs

  build_apk_release:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout

      - run:
          name: genarate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed

      - restore_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs

      - run:
          name: generate keystore debug
          command: |
            [ ! -d ~/.android ] && mkdir ~/.android
            echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - run:
          name: gradlew grand access
          command: |
            chmod +x gradlew

      - run:
          name: gradle dependencies
          command: |
            ./gradlew dependencies

      - save_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle

      - run:
          name: gradle clean assembleRelease
          command: |
            ./gradlew clean assembleRelease

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs
          destination: outputs

  build_apk_debug:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout

      - run:
          name: genarate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed

      - restore_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs

      - run:
          name: generate keystore debug
          command: |
            [ ! -d ~/.android ] && mkdir ~/.android
            echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - run:
          name: chmood gradlew
          command: |
            chmod +x gradlew

      - run:
          name: gradle dependencies
          command: |
            ./gradlew dependencies

      - save_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle

      - run:
          name: gradle clean assembleDebug
          command: |
            ./gradlew clean assembleDebug

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs
          destination: outputs

workflows:
  build:
    jobs:
      - build
      - build_aab
      - build_apk_release
      - build_apk_debug